services:

  threadlike.redis:
    image: redis:latest
    container_name: threadlike.redis
    restart: always
    ports:
      - 6200:6379

  threadlike.queue:
    image: rabbitmq:management-alpine
    container_name: threadlike.queue
    hostname: threadlike-queue
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5671:5672
      - 15671:15672  
  threadlike.seq: # handle logs
    image: datalust/seq:latest
    container_name: threadlike.seq
    hostname: threadlike-seq
    volumes:
        - ./.containers/seq/data/:/data
    environment:
        - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 5342:80
  threadlike.prometheus: # handle metrics
    image: prom/prometheus:latest
    container_name: threadlike.prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./.containers/prometheus:/prometheus
      - ./.containers/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  threadlike.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: threadlike.jaeger
    ports:
      - 4317:4317 # default port for the OpenTelemetry gRPC receiver.
      - 4318:4318 # default port for the OpenTelemetry HTTP receiver
      - 16686:16686 # where UI is 
    mem_limit: 200M
    environment:
      - MEMORY_MAX_TRACES=50000 # Limit the number of traces stored in memory
      - MEMORY_RETENTION=1h 


  threadlike.user.api:
    image: ${DOCKER_REGISTRY-}threadlikeuserapi
    container_name: threadlike.user.api
    build:
      context: .
      dockerfile: src/Modules/Users/ThreadLike.User.Api/Dockerfile
    volumes:
        - ./.data/Logfiles/Users/:/app/Logfiles/Users/
    depends_on:
      - threadlike.queue
      - threadlike.redis
    ports:
      - 8200:8080
      - 8201:8081

  threadlike.chat.api:
    image: ${DOCKER_REGISTRY-}threadlikechatapi
    container_name: threadlike.chat.api
    build:
      context: .
      dockerfile: src/Modules/Chats/ThreadLike.Chat.Api/Dockerfile
    volumes:
        - ./.data/Logfiles/Chats/:/app/Logfiles/Chats/
    depends_on:
      - threadlike.queue
      - threadlike.redis
    ports:
      - 8202:8080
      - 8203:8081

